wishes = [
    'Count your life by smiles, not tears. Count your age by friends, not years. Happy birthday!',
    'Happy birthday! I hope all your birthday wishes and dreams come true.',
    'May the joy that you have spread in the past come back to you on this day. Wishing you a very happy birthday!',
    'Forget the past; look forward to the future, for the best things are yet to come.',
    'You’re older today than yesterday but younger than tomorrow, happy birthday!',
    'Cheers on your birthday. One step closer to adult underpants.',
    'Happy birthday to one of the few people whose birthday I can remember without a Line reminder.',
    'Happy Birthday! You know, you don’t look that old. But then, you don’t look that young, either.',
    'To quote Shakespeare: ‘Party thine ass off!',
    'You are only young once, but you can be immature for a lifetime. Happy birthday!',
    'Happy birthday to someone who is forever young!',
    'Wishing you a day filled with happiness and a year filled with joy. Happy birthday!',
    'Sending you smiles for every moment of your special day',
    'Have a wonderful time and a very happy birthday!',
    'Sending your way a bouquet of happiness to wish you a very happy birthday!',
    'Wishing you a beautiful day with good health and happiness forever. Happy birthday!',
    'On this wonderful day, I wish you the best that life has to offer! Happy birthday!',
    'I wish for all of your wishes to come true. Happy birthday!',
    'Sending you a birthday wish wrapped with all my love. Have a very happy birthday!',
    'A simple celebration, a gathering of friends; here wishing you great happiness and a joy that never ends.',
    'It’s always a treat to wish happy birthday to someone so sweet.',
    'On this special day, I raise a toast to you and your life. Happy birthday.',
    'You look younger than ever! Happy birthday!',
    'I hope that today, at your party, you dance and others sing as you celebrate with joy your best birthday.'
]

emoji = [
    'ヾ(≧▽≦*)o',
    'φ(*￣0￣)q',
    '(≧▽≦q)',
    'ψ(｀∇´)ψ',
    '（￣︶￣）↗',
    '*^____^*',
    '(～￣▽￣)～',
    '( •̀ ω •́ )✧',
    '~(￣▽￣)~',
    '*φ(゜▽゜*)',
    '♪o(*^＠^*)',
    'oO(∩_∩)O',
    '(✿◡‿◡)',
    '`(*>﹏<*)′',
    '(*^▽^*)',
    '（*＾-＾*）',
    '(*^_^*)',
    '(❁´◡`❁)',
    '(≧∇≦)ﾉ',
    '(´▽`ʃ♡ƪ)',
    '(●ˇ∀ˇ●)',
    '(￣y▽￣)╭ Ohohoho.....',
    '○( ＾皿＾)っ Hehehe…',
    '(‾◡◝)',
    '╰(*°▽°*)╯',
    '(〃￣︶￣)人(￣︶￣〃)',
    '(/≧▽≦)/',
    'ㄟ(≧◇≦)ㄏ',
]
